#         ___ _                 _
#__  __ / __\ |__  _   _ _ __ | | __ /\  /\___  _ __  _ __   ___ _ __ ___
#\ \/ // /  | '_ \| | | | '_ \| |/ // /_/ / _ \| '_ \| '_ \ / _ \ '__/ __|
# >  </ /___| | | | |_| | | | |   </ __  / (_) | |_) | |_) |  __/ |  \__ \
#/_/\_\____/|_| |_|\__,_|_| |_|_|\_\/ /_/ \___/| .__/| .__/ \___|_|  |___/
#                                              |_|   |_|
#                 Web: https://xplugin.es
#          Wiki: https://xplugin.es/xchunkhoppers
#            Discord: https://discord.xplugin.es

settings:
  # Enable or disable the entire plugin functionality
  enabled: true

  # If true: Only collects items in 'filter-list'.
  # If false: Collects everything EXCEPT items in 'filter-list'.
  use-whitelist: false

  # List of materials (Use Bukkit Material enum names)
  filter-list:
    - "COBBLESTONE"
    - "DIRT"
    - "ROTTEN_FLESH"

# Menu GUI
menu:
  title: "&#B3B3B3Admin hoppers menu"
  size: 27
  fill:
    enabled: true
    material: "BLACK_STAINED_GLASS_PANE" # Material to fill empty spaces

# Hoppers
hopper-types:
  default:
    radius: -1
    name: "&#00ff00Chunk Hopper &7(16x16)"
    lore:
      - "&8 Special Item"
      - ""
      - "&f Place this block to"
      - "&f collect all items"
      - "&f in this chunk automatically."
      - ""
      - "&eWhole Chunk!"
      - ""
  vip:
    radius: 4
    name: "&#ffaa00Hopper &lVIP &7(8x8)"
    lore:
      - "&8 VIP Item"
      - ""
      - "&f Place this block to"
      - "&f collect all items"
      - "&f in this chunk automatically."
      - ""
      - "&eWhole Chunk!"
      - ""
  god:
    radius: 32
    name: "&#ff0000Hopper &lGOD &7(64x64)"
    lore:
      - "&8 GOD Item"
      - ""
      - "&f Place this block to"
      - "&f collect all items"
      - "&f in this chunk automatically."
      - ""
      - "&eWhole Chunk!"
      - ""

# Configuration for effects when placing the Hopper and using the Menu
effects:
  sound:
    enabled: true
    # Sound names: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
    type: "ENTITY_PLAYER_LEVELUP"
    volume: 1.0
    pitch: 1.0
  particles:
    enabled: true
    type: "VILLAGER_HAPPY"
    count: 15

permissions:
  admin: "xchunkhoppers.admin"
  place: "xchunkhoppers.place"
  break: "xchunkhoppers.break"

messages:
  prefix: "&8[&d&lxCH&8] "
  no-permission: "&cYou do not have permission to do this."
  reload: "&#00ff00Configuration and Data reloaded successfully."
  player-not-found: "&cPlayer not found."
  give-success: "&aYou gave &e%amount% &f%type% &a to &f%player%&a."
  received: "&aYou have received a &dChunk Hopper&a."
  placed: "&#00ff00Chunk Hopper placed! It will now collect items in this range."
  broken: "&eYou have removed the Chunk Hopper."
  already-exists: "&cThere is already a Chunk Hopper here."
  type-not-found: "&cThat Hopper type does not exist in the config."

version: 1.0.0